### ISSUE TITLE
Create capsules detection and API

### ISSUE THREAD

**Issue by RoySegall** [RoySegall/nuntius-bot#102]
The capsules need to be located in two places:
1. `core`
2. `capsules`

In each capsule library we need to have a file called `CAPSULE_NAME.capsule.yml`. The file will be constructed by:
```yml
name: slack
dependencies:
  - system
```

In order to integrate with the hooks and plugins mechanisim we need to have `CAPSULE_NAME.services.yml`. This file will consturcted like this:
```yml
services:
  slack_handler:
    class: \Nuntius\Capsules\Slack\Services\SlackHandler
    arguments: ['@db']
hooks:
  slack_handler_entity_create:
    class: \Nuntius\Capsules\Slack\Hooks\SlackHandlerEntityCreate
    hook: entity_create
plugins:
  entieis:
    # This will ensure all the classes in this namepsace will tag as an entity plugin
    namespace: \Nuntius\Capsules\Slack\Plugins\Entity
    plugin: entity
  logger:
    # This will ensure all the classes in this namepsace will tag as an entity plugin
    namespace: \Nuntius\Capsules\Slack\Plugins\Logger
    plugin: logger
```
