### ISSUE TITLE
Add Facebook bot response manager

### ISSUE THREAD

**Issue by RoySegall** [RoySegall/nuntius-bot#92]
For now, menus and other stuff send payload to the server then the server send to the user buttons payload and then the user click on the button and we need to return another payload.

Let's make another serivce in the YML file:
```yml
facebook_payload:
  'list_of_foods': 'namepsace'
  'save_me': 'namepsace'
```
